### ISSUE TITLE
Choco Meteor installer hangs when extracting to AppData/Local

### ISSUE THREAD

**Issue by SammyIsra** [meteor/meteor-chocolatey-installer#1]
OS: Windows 10 Pro Build 15063
Choco version: 0.10.7

I tried installing Meteor on Windows twice via the command `choco install meteor`. Both times the installation seemed to go as expected until it tried to extract `C:\Users\<me>\AppData\Local\Temp\chocolatey\meteor\0.0.1\meteor-bootstrap-os.windows.x86_64.tar` to `C:/Users/<me>/AppData/Local` where it hangs and seems to not progress at all. 

I tried this on both Powershell and regular command prompt. In both cases, it hung for around 20+ minutes with no response. I was able to `Ctrl+C` out without issue.

When trying to install again, Choco removes the incomplete install of Meteor

**Comment by SammyIsra** [comment]
I managed to make it work, the mistake was on my side. Choco was timing out and the message was not displaying on the console that I was using (Cmder). 

If I run it on PowerShell it does show the timing out error message, and running `choco install meteor -y --execution-timeout 10000` will allow the process to finish.

**Comment by Akagilnc** [comment]
same error in power shell.
I think it's a bug

**Comment by abernix** [comment]
@DeronLee please try disabling Windows Defender or other anti-virus software during the installation and see if that helps with the problem.

**Comment by cinderblock** [comment]
I had this issue as well.

I could watch the folder properties of `%LOCALAPPDATA%\.meteor` and see the total number of files and size increase until it matched the ~772MB of the `tar` archive that was being extracted. Then the installer just sat there. I left it for a couple hours with no change. The "Antimalware Service Executable" was taking up 10% of my CPU time, more than any other process.

I tried to install with `--execution-timeout 10000` to no avail.

What fixed this for me was temporarily disabling the "Real-time protection" of Windows Defender. After re-running the installer, it still paused for maybe a minute on the "Extracting ..." step but, in the end, worked itself out and now I can run `meteor` from cli.

**Comment by JoeyFenny** [comment]
Disabling Windows Defender (real-time protection) and running `choco install meteor -y --execution-timeout 10000` in Powershell (rather than CMD) as an admin fixed the problem for me.

**Comment by kumarravigithub** [comment]
I installed it from here and got Meteor 1.6.1 installed on my Windows 10 system and it works perfectly.
https://install.meteor.com/windows

**Comment by abernix** [comment]
@techsavyravi That will work, but keep in mind it will be a 32-bit version of Meteor 1.6.1 (and Node, Mongo, etc.) rather than the more performant 64-bit version.  64-bit is only available through the Chocolatey install, but if you're ok with that, go right ahead and use the older installer!

**Comment by sandro-heitz** [comment]
And what do I do, if I cannot disable defender or other anti virus programs?

**Comment by x5engine** [comment]
@sandro-heitz Have you tried turning it off and on again? are you sure it is plugged in?

**Comment by Hamidreza-Sedigh** [comment]
I try to install meteor with Chocolatey on windows 10. use both powershell and cmd as administrator. I turned off the windows firewall and windows Defender but still I get the error. it seems others have this problem but it didn't solve for me. If this is not very related to this issue I open a new one:
```Downloading meteor 64 bit
  from 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64'. Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server"
This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
The install of meteor was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\meteor\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - meteor (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\meteor\tools\chocolateyinstall.ps1'.
 See log for details.```

**Comment by cinderblock** [comment]
@Hamidreza-Sedigh Looks like a different error.

Side note, it looks like you tried to mark the error you copied as `code` but failed to use the correct number of ticks. Note that triple backticks (` ``` `) are required for blocks of code and single backticks are used for inline snippets. Make sure you check the "Preview" before posting and that it looks like you expect.

**Comment by lukewatts** [comment]
Yeah lets just turn off our anti-virus every time we install new things...

**Comment by fakabbir** [comment]
One easy way would be to open 7zip in admin mode and extract it to the Local directory. You need to get the path added to the environment variable too.
