### ISSUE TITLE
Address Chocolatey moderator's suggestions.

### ISSUE THREAD

**Issue by abernix** [meteor/meteor-chocolatey-installer#10]
When the 0.0.2 package was approved (today), it was suggested by the Chocolatey moderator to make the following changes in future releases of this installer:

* add additional tags like 'javascript', 'dev'
* add a summary
* add checksums

The first two are straightforward, and this is simply a reminder issue for myself or the next person to publish this package.  I've added this issue to the 0.0.3 milestone accordingly.

The "add checksums" item is a bit more difficult since Meteor is internally responsible for its own version spring-boarding and the package which is downloaded (securely from our package server, via the [bootstrap link](packages.meteor.com/bootstrap-link), which always returns the _latest_ version) will change when a new version comes out.  This would cause the checksum in this Chocolatey package's nuspec to become outdated.  In fact, having specific checksums for each release (and thus different installers for each version) would actually be detrimental since each Chocolatey install would wipe out all other versions of Meteor on that workstation, which might all be getting used concurrently if a developer works on a apps with different Meteor versions.

Overall, this might simply be a matter of communicating this to the Chocoloatey package moderators.  They brought it up for the 0.0.1 release as well.  It's certainly a good practice for Chocolatey packages in general (which generally have a single most recent version and old versions are never used again), however Meteor is different and it wouldn't be practical with our current setup to have a checksum.

**Comment by filipenevola** [comment]
This installer is deprecated.

https://meteor.com/developers/install
