### ISSUE TITLE
Unable to install previous versions - 403 Forbidden

### ISSUE THREAD

**Issue by joshuadavidson** [meteor/meteor-chocolatey-installer#11]
OS: Windows 10 Pro, 64-bit

I have a system with Meteor currently uninstalled (`choco uninstall meteor` was run first). When running `choco install meteor --params="'/RELEASE:1.4.4.5'"` or `choco install meteor --x86 --params="'/RELEASE:1.4.4.5'"` per the "[Installing a specific version of Meteor](https://github.com/meteor/meteor-chocolatey-installer#installing-a-specific-version-of-meteor)" section of the readme the following 403 error message is produced:
```
Attempt to get headers for https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_32&release=1.4.4.5 failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_32&release=1.4.4.5'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
Downloading meteor 32 bit
  from 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_32&release=1.4.4.5'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_32&release=1.4.4.5'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
The install of meteor was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\meteor\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - meteor (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\meteor\tools\chocolateyinstall.ps1'.
 See log for details.
```
I am willing to take a stab a PR but to me it looks as though the 403 error is coming from the host of the meteor gzip file. For what it is worth, when visiting the URL that choco uses to download meteor at [https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_32&release=1.4.4.5](https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_32&release=1.4.4.5) the XML produced looks like an AWS S3 permissions error.

**Comment by abernix** [comment]
It's occurred to me that the 1.4.4.5 release was published without the so-called "bootstrap tarballs", which would enable a developer to perform direct installation of an older version with the `--params="'/RELEASE:x.y.z'"` flag, whereas the default (without the flag) would just use the _latest_ bootstrap tarballs—Meteor 1.6.0.1, as of right now.  We usually always publish them, but this was an update to the not actively developed 1.4.4.5 line to allow developers to do a simple `meteor update` to that version, which would be handled without the bootstrap tarballs.

Directly installing an older version isn't super common/recommended/always-necessary, but in your particular case, it may be the easiest way for you to move forward.  Therefore, I've gone ahead and published them.  Care to try again?  Hope this helps.

**Comment by joshuadavidson** [comment]
It worked! Thank you this really helps our team out and is a much better solution than the workaround in meteor/meteor#9283.

For others finding this issue here is what I ran to get version 1.4.4.5: 
1. Run `choco uninstall meteor` to clear out your `%localappdata%/.meteor` folder.
2. Run `choco install meteor --x86 --params="'/RELEASE:1.4.4.5'"` to install only version 1.4.4.5.

**Comment by abernix** [comment]
Awesome. I'll close this since this means the Chocolatey installer is working properly.  We should definitely focus on getting the core problem which is preventing you from upgrading to newer versions resolved though!  That's best done through the issue on meteor/meteor though.  Thanks for reporting this originally!
