### ISSUE TITLE
Git Bash Compatability

### ISSUE THREAD

**Issue by Jared-Dev** [meteor/meteor-chocolatey-installer#12]
Git Bash is a substantial improvement over the command prompt or the Powershell terminal (IMO). Is there any mechanism that would allow the meteor CLI to work? Just so it is clear I don't actually want to use Bash that is included with the Linux Sub-System that Windows offer, but just from Git Bash. I actually believe it should work as is, but there is a check that seems to prevent it from even running...

Additional Info...
When attempting to use the OSX/Linux installers it provides this message from within Git Bash...
```
To install Meteor on Windows, download the installer from:
https://install.meteor.com/windows
```

**Comment by filipenevola** [comment]
This installer is deprecated.

https://meteor.com/developers/install
