### ISSUE TITLE
Choco Meteor installer hangs when extracting to AppData/Local

### ISSUE THREAD

**Issue by pilarArr** [meteor/meteor-chocolatey-installer#8]
I have the same issue as #1 but the solution there does not work for me.

I'm trying to install Meteor on a Lenovo miix320 with windows 10.

The installer hangs on the second extraction. This is the output of the verbose install command.
I've executed the installer and I'm currentlty 20 minutes in, no signs of advance.

https://gist.github.com/pilarArr/e6e3643a5022c6314b735e616d4c7a75

**Comment by pilarArr** [comment]
Nevermind, the second extraction just started. I'll close the issue when the installer finishes the installation

**Comment by abernix** [comment]
Turning off Windows Defender or any other virus scanner will help tremendously.  I'd be interested in seeing the final output in Gist form!

**Comment by pilarArr** [comment]
I'm sorry @abernix I didn't save the second gist. 
What I did to get this to work was restoring windows to a clean slate with the recovery option in windows 10.  It was a new computer also.
Everything worked after that. It took around 30 minutes to do the installation, but it finally went through. I'll probably have to do the installation in another computer next week, if I have this issue again I'll post the gist.

I finally had to do the installation of `choco install meteor` with powershell as instructed in issue #1 
The installation of `chocolatey` worked fine from `cmd.exe`, but the `choco install meteor` only worked from the powershell

**Comment by abernix** [comment]
Thanks for the follow-up.  I'll close this until you run into problems again.

I haven't tested `choco install` from `cmd.exe`, but since Microsoft is trying to sunset it, I'm not sure how much effort we'll put into making that work.  PRs encouraged!
